from PySideX.QtWidgetsX.modules.styles.style import EnvStyle
from PySideX.QtWidgetsX.modules.styles.stylecinnamon import EnvStyleCinnamon
from PySideX.QtWidgetsX.modules.styles.stylegnome import EnvStyleGnome
from PySideX.QtWidgetsX.modules.styles.stylemac import EnvStyleMac
from PySideX.QtWidgetsX.modules.styles.stylemate import EnvStyleMate
from PySideX.QtWidgetsX.modules.styles.styleplasma import EnvStylePlasma
from PySideX.QtWidgetsX.modules.styles.stylewindows7 import EnvStyleWindows7
from PySideX.QtWidgetsX.modules.styles.stylewindows10 import EnvStyleWindows10
from PySideX.QtWidgetsX.modules.styles.stylewindows11 import EnvStyleWindows11
from PySideX.QtWidgetsX.modules.styles.stylexfce import EnvStyleXFCE
