from .style import EnvStyle
from .stylecinnamon import EnvStyleCinnamon
from .stylegnome import EnvStyleGnome
from .stylemac import EnvStyleMac
from .stylemate import EnvStyleMate
from .styleplasma import EnvStylePlasma
from .stylewindows7 import EnvStyleWindows7
from .stylewindows10 import EnvStyleWindows10
from .stylewindows11 import EnvStyleWindows11
from .stylexfce import EnvStyleXFCE
